remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 


title: Clement Yuen
description: blah blah blah
logo: assets/img/logo.png
show_downloads: true

theme: jekyll-theme-minimal
