remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 


title: Clement Yuen
description: - Versatile analyst with working experience in both private and government sectors
- blah blah blah
logo: assets/img/profile.jpg
show_downloads: true

theme: jekyll-theme-minimal
